version: '3'

services:



  app:
    build:
      context: ./app/backend
      dockerfile: docker/docker_files/Dockerfile.prod
      cache_from:
        - "${PROD_APP_IMAGE}"
    image: "${PROD_APP_IMAGE}"
    restart: unless-stopped
    command: >
      gunicorn --env DJANGO_SETTINGS_MODULE=course.conf.prod course.wsgi.prod:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - main_course_network
    volumes:
      - ./backend:/code
      - /var/log/course:/code/logs

networks:
  main_course_network:
    driver: bridge
