# version: '3'

services:

  app:
    image: "${APP_IMAGE}"
    restart: unless-stopped
    command: >
       
       gunicorn -c gunicorn.conf.py --env DJANGO_SETTINGS_MODULE=course.conf.prod course.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/code
      - /var/log/course:/code/logs
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - main_course_network
    container_name: app


networks:
    main_course_network:
        driver: bridge
